# encoding: utf-8
---

- set_fact:
    package_url: "https://_:{{ instana_agent_agent_key }}@packages.instana.io"
    deb_architecture: {
      "aarch64": "arm64",
      "x86_64": "amd64"
    }

- name: Debug message
  ansible.builtin.debug:
    msg: "{{ [ansible_architecture] | map('extract', deb_architecture) | first }}"

- name: 'add apt key'
  apt_key:
    state: present
    url: https://packages.instana.io/Instana.gpg
  when: ansible_pkg_mgr == 'apt'

- name: 'add apt repository'
  ansible.builtin.apt_repository:
    repo: "deb [arch={{ [ansible_architecture] | map('extract', deb_architecture) | first }}] {{ package_url }}/agent generic main"
    state: "present"
  when: ansible_pkg_mgr == 'apt'

- name: 'add rpm key'
  rpm_key:
    state: present
    key: https://packages.instana.io/Instana.gpg
  when: ansible_pkg_mgr == 'yum' or ansible_pkg_mgr == 'zypper'

- name: 'add zypper repo'
  zypper_repository:
    enabled: yes
    name: "Instana-Agent"
    repo: "{{ package_url }}/agent/generic/x86_64"
    state: "present"
  when: ansible_pkg_mgr == 'zypper'

- name: dons message
  ansible.builtin.debug:
    msg: "{{ ansible_pkg_mgr }}"

- name: 'add yum repo'
  yum_repository:
    baseurl: "{{ package_url }}/agent/generic/x86_64"
    description: 'The Agent repository by Instana, Inc.'
    enabled: yes
    gpgcheck: no
    name: 'Instana-Agent'
  when: ansible_pkg_mgr == 'yum'
